package cn.powernukkitx.techdawn.item;

import cn.nukkit.item.ItemTool;

public interface ItemConstants {
    int DURABILITY_WOODEN = ItemTool.DURABILITY_WOODEN;
    int DURABILITY_STONE = ItemTool.DURABILITY_STONE;
    int DURABILITY_IRON = ItemTool.DURABILITY_IRON;
    int DURABILITY_DIAMOND = ItemTool.DURABILITY_DIAMOND;
    int DURABILITY_GOLD = ItemTool.DURABILITY_GOLD;
    int DURABILITY_NETHERITE = ItemTool.DURABILITY_NETHERITE;
    int DURABILITY_COPPER = 192;
    int DURABILITY_TIN = 132;
    int DURABILITY_BRONZE = 255;
    int DURABILITY_TOUGH_COPPER = 1471;
    int DURABILITY_ANNEALED_COPPER = DURABILITY_GOLD;
}
