name: TechDawn
main: cn.powernukkitx.techdawn.Main
version: "0.0.1"
api: ["1.0.14"]
load: POSTWORLD
author: PowerNukkitX dev team
authors: ["Superice666"]
description: TechDawn reborn on PNX
website: https://github.com/PowerNukkitX/TechDawn

permissions:
  techdawn.all:
    description: "Allows the user to control all techdawn options"
    default: op