name: Build with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive Libraries
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: ModPack
        path: target/libs/TechDawn-*.jar
    - name: Archive Libraries
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: ResourcePack
        path: target/libs/TechDawn.mcpack
